stages:
  - lint

flake8:
  stage: lint
  image: python:3.12
  before_script:
    - pip install flake8
  script:
    - flake8 .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
