FROM python:3.11-slim

WORKDIR /app
RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false

RUN poetry install --no-root --with tgnotifier
COPY telegram_notifier.py .

CMD ["python", "telegram_notifier.py"] 