api:
  host: 0.0.0.0
  port: 8080
  workers: 4
database:
  db_name: document_comparison
  uri: mongodb://localhost:27017/
metrics:
  collection_name: model_metrics
  storage_path: metrics
models:
  default: parseq
  paths:
    master: models/master.pt
    parseq: models/parseq.pt
  version: v4
