name: Lint with flake8

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.12
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify .flake8 exists
      run: |
        if [ ! -f .flake8 ]; then
          echo "Error: .flake8 config file not found!"
          exit 1
        fi
        cat .flake8  # Optional: Display config for debugging
    
    - name: Install flake8
      run: pip install flake8
      
    - name: Run flake8 with config
      run: flake8 .