name: Lint with flake8

on:
  push:
    branches: [ main ]  # Replace with your default branch name
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.12
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install flake8
      run: pip install flake8
      
    - name: Run flake8
      run: flake8 .
